name: cs236-dp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - black
  - tqdm
  - cudatoolkit=11.1
  - torchaudio
  - torchvision
  - pytorch
  - tensorboard
  - ignite
  - scipy
